site_name: PG LAB Electronics Docs 
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    

  language: en
  logo: img/logo.png
  favicon: img/favicon.png
  palette:
    
    - scheme: default
      primary: orange
      accent: purple 
  icon:
    admonition:
        note: octicons/tag-16
        abstract: octicons/checklist-16
        info: octicons/info-16
        tip: octicons/squirrel-16
        success: octicons/check-16
        question: octicons/question-16
        warning: octicons/alert-16
        failure: octicons/x-circle-16
        danger: octicons/zap-16
        bug: octicons/bug-16
        example: octicons/beaker-16
        quote: octicons/quote-16
nav:
    - HOME: index.md

    - E-BOARD:
      - HARDWARE: eboard/eboard.md
      - SETUP:
        - REQUIREMENTS: eboard/requirements.md
        - INSTALLATION: eboard/installation.md
        - FIND IP: eboard/find-ip.md
      - WEB SERVER:
        - INTRO: eboard/webserver-intro.md
        - RELAY: eboard/webserver-relay.md
        - SHUTTER: eboard/webserver-shutter.md
        - NETWORK: eboard/webserver-network.md
        - SETTING: eboard/webserver-setting.md
        - REBOOT: eboard/webserver-reboot.md
        - ABOUT: eboard/webserver-about.md
        - FIRMWARE: eboard/webserver-firmware.md
      - CONNECTIVITY:
        - MQTT: eboard/mqtt.md
        - HOME ASSISTANT: eboard/homeassistant-integraton.md
        - PYTHON: eboard/python.md

    - E-RELAY: 
      - HARDWARE: erelay/erelay.md
      - SETUP:
        - REQUIREMENTS: erelay/requirements.md
        - INSTALLATION: erelay/installation.md        
        - WIRING: erelay/wiring.md

    - E-VLXESP32: 
      - HARDWARE: evlxesp32/evlxesp32.md


markdown_extensions:
  - admonition
  - tables
  - attr_list
  - def_list
  - markdown_grid_tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
extra_css:
  - style.css